server:
  port: 9899

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

tenant:
  base-port: 5500

app:
  base-url: jdbc:postgresql://localhost
  aes:
    secure-key: 12345678901234567890123456789012
  rabbitmq:
    exchange: tenant.identity.exchange

spring:
  application:
    name: TENANT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    unsa:
      sistemas:
        tenantservice: DEBUG

