server:
  port: 9899

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

tenant:
  base-port: 5500

app:
  base-url: jdbc:postgresql://localhost
  aes:
    secure-key: 12345678901234567890123456789012
  rabbitmq:
    exchange: tenant.identity.exchange
    routing-key: tenant.database.created

spring:
  application:
    name: TENANT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/tenant-service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
